### ISSUE TITLE
`enonic sandbox stop` - using wrong PID on Mac.

### ISSUE THREAD

**Issue by jsi** [enonic/enonic-cli#108]
If a sandbox is started on Mac, and I either try to start another or just stop it, it has to be done from another terminal window.  This seems to always result in an error that there is no such process.  Example:
`Could not stop process 35262 no such process`

The PID seems to always be one number to high.  For instance in the error above, the actual PID was 35261.

**Comment by pmi** [comment]
@jsi Pretty sure it should be fixed now, but cannot test it on mac myself so need your confirmation

**Comment by jsi** [comment]
I can confirm that this works in 0.5.3!  :)
