### ISSUE TITLE
Cant run `project build`

### ISSUE THREAD

**Issue by poi33** [enonic/enonic-cli#112]
Using the command "enonic project build" fails on the java execution:

![image](https://user-images.githubusercontent.com/3340349/54032984-6f135480-41b3-11e9-94de-1c4565caa76e.png)

**Comment by sigdestad** [comment]
Which version of enonic-cli have you installed? And when did you install it?

**Comment by pmi** [comment]
And also where did you get the project you tried to build ? Most importantly which gradle version it uses ?

**Comment by poi33** [comment]
Did not manage to build the CLI so i downlouded it from the repo.
The version is 5.3 64-bit
Managed to get it to build today. 
The project is the vanilla starter (on branch xp-7.0.0 ). 

I'll close this as i did not manage to reproduce this error.
