### ISSUE TITLE
Check out permissions problem with enonic binary executable

### ISSUE THREAD

**Issue by sigdestad** [enonic/enonic-cli#83]
This might cause problems with mac/linux distros. Must set permissions manually right now.

**Comment by sigdestad** [comment]
Is there a 0.4 build with this info available?

**Comment by sigdestad** [comment]
Hmm..  for XP distro's we have this info in the binaries? How is this different for cli?

**Comment by pmi** [comment]
cli is built on windows, and xp is not I presume. Problem with windows is the ntfs drive which [does not support](https://stackoverflow.com/questions/8852344/how-can-i-use-chmod-command-under-the-ntfs-file-system) permissions per file :(

**Comment by pmi** [comment]
I have checked in a fix, but it has to be run on mac or linux

**Comment by pmi** [comment]
Maybe windows with non-ntfs drive is ok too, but mine came with ntfs formatted drive

**Comment by sigdestad** [comment]
Will you create task and talk to Jørgen?

**Comment by pmi** [comment]
Yup

**Comment by jsi** [comment]
Error in config corrected in v0.5.1
