### ISSUE TITLE
Not correct response in console, when not existing URL was typed in "install command"

### ISSUE THREAD

**Issue by sgauruseu** [enonic/enonic-cli#92]
**CASE 1**
1. Type the command `enonic app install`
2. Type `http://my.apps.com/myapp.jar` in URL input

**BUG**: 
**Expected**: "Failed to process application from http://my.apps.com/myapp.jar"  should appear
**Actual** -  "Installed " message appears in the console 

![image](https://user-images.githubusercontent.com/3728712/52409267-15513900-2ae6-11e9-82fd-8dcdcb4e5a8e.png)

**CASE 2**
1. Type the command `enonic app install`
2. Type a path to existing JPG file

BUG; "Installed" message appears 

![image](https://user-images.githubusercontent.com/3728712/52409756-77f70480-2ae7-11e9-88b8-a4455697fd24.png)

**Comment by pmi** [comment]
response is considered valid if Faliure text is empty, and it looks like it always is.
So this looks like an api issue, rather than cli's

**Comment by pmi** [comment]
What do you think @GlennRicaud ?

**Comment by pmi** [comment]
Failure was mapped incorrectly in cli itself. Fixed that.
