### ISSUE TITLE
Number of replicas should be limited

### ISSUE THREAD

**Issue by sgauruseu** [enonic/enonic-cli#93]
1. Type the command  `enonic cluster replicas`
2. Type the number -  6709867

**Bug**: 
**Expected** - user input should be limited (max number or replicas is 50?)

**Actual**: **Error in console** 
**After setting a large number of replicas, the service stops working**. And it does not work even with 2 replics(see the screenshot)
 
![image](https://user-images.githubusercontent.com/3728712/52413442-b7771e00-2af2-11e9-8696-1f4dcec51b24.png)

**Exception in the server log**
`c.e.x.j.i.e.JsonExceptionMapper - Failed to update index: search-com.enonic.cms.default
com.enonic.xp.repository.IndexException: Failed to update index: search-com.enonic.cms.default`

**Comment by pmi** [comment]
Limited to 1-99 interval
