### ISSUE TITLE
Tuning of management commands and structure

### ISSUE THREAD

**Issue by sigdestad** [enonic/enonic-cli#95]
To make things, I suggest the following change to our structure

New command structure then looks like this:

* app (no change)
* cms (no change)
* export
** create (renamed from new)
** list
** remove
** import (renamed from load?)
* snapshot
** create (rename from new)
** list
** remove
** restore
* repo
** list (new command to list available repos)
** reindex
** readonly
** replicas (moved from cluster)
* dump
** create (renamed from new)
** list (new command to list dumps)
** upgrade
** load
* system
** info (new command to show info about XP, should get this from request to :4848/

**Comment by pmi** [comment]
@tsi Where can I get available repos ? Should I create new endpoint for that ?

**Comment by sigdestad** [comment]
We are working on the endpoint now Pavel.. Hopefully live tomorrow!

**Comment by pmi** [comment]
Cool ! Waiting for it then, the rest is ready !
