### ISSUE TITLE
Better handling of network dependencies

### ISSUE THREAD

**Issue by sigdestad** [enonic/enonic-cli#98]
When trying to create new sandbox it was hangs after asking for name.
After waitinig for quite a while, finally a 503 error message appears.

Let us improve how this works:
* I guess, we should have some kind of feedback/spinner when we are connecting to an external source and waiting for it to respond. 
* If it fails, we need a more presise response, i.e. "unable to connecto to enonic cloud services" or something like that?
* Also, I guess timeout could be slightly shorter?

**Comment by pmi** [comment]
* added spinner to all requests
* reduced timeout for fast requests to 1 min
* updated error message
