### ISSUE TITLE
Automatically stop other sandbox

### ISSUE THREAD

**Issue by sigdestad** [enonic/enonic-cli#99]
When trying to start a new sandbox, it will check if other sandboxes are running and tell you to stop it first. Can we improve this:

* Tell user "Sandbox xx" is running, do you want to stop it (Y/n)
* If Y, stop other sandbox with a soft "kill" command, and then start the current sandbox.

NB! I am not sure how this works on windows, but should not be a problem to stop other processes on linux/mac

**Comment by pmi** [comment]
@tsi Stopping  running sandbox includes most of the code I wrote for the starting sandbox in a detached mode, so maybe we should include that option also ?

**Comment by sigdestad** [comment]
What is "detached mode"?

**Comment by sigdestad** [comment]
Like running in the background?

**Comment by pmi** [comment]
exactly, there was a [task ](https://github.com/enonic/enonic-cli/issues/37) to investigate it, but the PR has never been pulled

**Comment by sigdestad** [comment]
I see, let's prioritize the core tasks of the CLI before we continue on this.

**Comment by pmi** [comment]
Pushed it since it has been already completed. We can delete it any time if not needed, although I wouldn't like to do it ;)
